customhost = "employee.crgvljvdc5s5.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "admin123"
customdb = "employee"
custombucket = "my-project2"
customregion = "US East (N. Virginia) us-east-1"
